### ISSUE TITLE
Simlib sampling for ToO

### ISSUE THREAD

**Issue by rbiswas4** [rbiswas4/OpSimSummary#275]
There is a potential need to prioritize simlib locations for ToO. In the scheme of sampling today, a ToO location might not get sampled, which has a larger effect on ToO studies than other regions randomly not getting sampled.

**Comment by soares-santos** [comment]
Hi, I thought about this issue. I think it is not a problem if the sampled locations are the same when we rerun the code on the overwritten.db. 
- say we run the opsimsumary code on the input from opsim, and sample 50K locations. SNANA will put events on those locations.
- now we run the owsim code from eric and have TOO visits following the desired in the kilonova locations. these locations are, by default, a subset of the 50K locations above. 
- finally, we rerun opsimumary on the overwritten db. if the 50K locations are the same as before, we should pick up the locations of the TOO visits. but if they are a new random sample, then we have no guarantee that the kilonovae are going to be generated in the same places! 
- @rbiswas4 is it possible to fix the randomseed that you use in the sampling, so that we can repeat the same 50K locations when we run the code on the owsim outputs?
