### ISSUE TITLE
Turn Nulls off

### ISSUE THREAD

**Issue by rbiswas4** [rbiswas4/OpSimSummary#276]
Currently, the overwritten database that is available contains the following columns `proposals`, `angle`, `sunRA` and `sunDec` with `None` values. Due to various checks in my code, I do not wish to allow null values in the database table source. 

Two possible ways out are:
- [ ] Remove these columns, easy.
- [ ] Keep these columns but calculate real values for them ... harder, perhaps useful later on, but not useful immediately.

@ehneilsen

**Comment by rbiswas4** [comment]
@ehneilsen : This is for you.

**Comment by ehneilsen** [comment]
Except for the "proposals" column, which I seem to have added by accident, these columns seem to be present in some opsim databases provided by the project, but not others. My code calculates values for sunRA and sunDec, and when I write the new database file, NULLs are added to the original exposures when they weren't in the original database (and propagates them they are).

"angle" is another case where it is in some database produced by opsim, but not others. I don't seem to be calculating it correctly, though: it looks like it is always 0 in the output database. This is clearly a bug in owsim.

Although it these cases it is the origin (opsim produced) databases that are missing columns (and so result in NULLs in the output database), given that not all databases produced by opsim have the same set of columns, we also need to consider the case where new columns are added in opsim. Should owsim break in these cases, or go ahead and create a database that simply has NULLs in columns it doesn't calculate? I think the later is the best behavior, because it doesn't make code fail when there is no reason it needs to.

So, I can see the argument for removing the "proposals" column, and I need to fix the value I write for "angle", but I disagree about not writing NULLs. If all data we know for each entry is included in the database, the database is maximally useful. If there is an entry for which we don't have a value, a NULL seems perfectly appropriate. If test code can't handle NULLs in columns that it doesn't need anyway, I think that is a problem in the tests, not the database.

**Comment by ehneilsen** [comment]
I've just pushed changes to the owsim github repo to remove the proposals column and the angle column (which might have been good to have, but it's broken anyway). I'll write a separate, stand-alone command to remove columns with nulls if it's really necessary.

**Comment by rbiswas4** [comment]
@ehneilsen Sorry, I did not not notice your posts yesterday. Thinking about it, I agree that test code should be able to handle NULL entries. So, I will make changes accordingly. 

In terms of `owsim` behavior:
> Should owsim break in these cases, or go ahead and create a database that simply has NULLs in columns it doesn't calculate? I think the later is the best behavior, because it doesn't make code fail when there is no reason it needs to.

I suppose by `break` here you mean not write out the column if it did not exist? 

I actually think the OpSim DB schema should be more uniform than this. Maybe that is a request to make to the OpSim folks.

**Comment by ehneilsen** [comment]
> I actually think the OpSim DB schema should be more uniform than this. Maybe that is a request to make to the OpSim folks.

@rbiswas4, I think it may be uniform with respect to specific versions of opsim -- for example it looks like the simulations that are provided by a given round of opsim4 runs (such as in the call for whitepapers) are the same. However, these differ from previous versions, and I will not be surprised if there are changes is future versions. Given how active the development of opsim is, I think it perfectly reasonable that the contents of the output not be set in stone.

**Comment by rbiswas4** [comment]
@ehneilsen Yes. I think it is fine if it is the same in a particular version. If there is a clear version difference between your outputs, that will be good too.
